# Jestでasync関数をテストする

参考: https://jestjs.io/ja/docs/asynchronous#asyncawait
参考書籍: フロントエンド開発のためのテスト入門

## 正常系

async-awaitで書ける
```ts
test("成功すること", async () => {
  expect(await fetchData()).toBe('success data');
});
```

## 異常系 (throw Error)

### rejectsを使う場合
expectにawaitをつけることに注意
```ts
test("失敗すること", async () => {
  await expect(asyncFunc()).rejects.toBe("error message")
});
```

### try-catchを使う場合
`expect.assertions(1);` を使うことで「アサーションが1回実行されること」を宣言できる
```ts
test("失敗すること", async () => {
  expect.assertions(1); // アサーションが1回実行されることを期待する
  try {
    await asyncFunc();
  } catch (e) {
    expect(e).toBe("error message")
  }
});
```
